version: "3.8"
services:
  vectoraidb:
    image: docker.io/williamimoh/actian-vectorai-db:latest
    container_name: context8_db
    ports:
      - "50051:50051"
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 2m
